version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
    - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: micro
      MYSQL_PASSWORD: stream
      MYSQL_DATABASE: microstream

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  postgres:
    image: postgres
    ports:
      - "45432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "53603:53603"
      - "48080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root